_BASE_: "../Base-RCNN-C4.yaml"
DATASETS:
  SOURCE_DOMAIN:
    TRAIN: ("kitti-car_train",)
  TARGET_DOMAIN:
    TRAIN: ("cityscapes-car_train",)
  TRAIN: ("kitti-car_train",)
  TEST: ("cityscapes-car2_val",)
MODEL:
  META_ARCHITECTURE: "SAPRCNN"
  BACKBONE:
    FREEZE_AT: 1
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  KEYPOINT_ON: False
  MASK_ON: False
  DOMAIN_ADAPTATION_ON: False
  ROI_HEADS:
    NUM_CLASSES: 1
  DA_HEAD:
    IN_FEATURE: "res4"
    IN_CHANNELS: 1024
    NUM_ANCHOR_IN_IMG: 5
    EMBEDDING_KERNEL_SIZE: 3
    EMBEDDING_NORM: True
    EMBEDDING_DROPOUT: True
    FUNC_NAME: "cross_entropy"
    POOL_TYPE: 'avg'
    LOSS_WEIGHT: 1.0
    WINDOW_STRIDES: [2, 2, 2, 2, 2, 2, 2, 2, 2]
    WINDOW_SIZES: [3, 6, 9, 12, 15, 18, 21, 24, 26]
  PROPOSAL_GENERATOR:
    NAME: "SAPRPN"
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 600
SOLVER:
  IMS_PER_BATCH: 2 # batch size
  STEPS: (61000,)
  BASE_LR: 0.001
  MAX_ITER: 70000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
VIS_PERIOD: 2000
SEED: 35839812