_BASE_: "../Base-RCNN-C4.yaml"
DATASETS:
  SOURCE_DOMAIN:
    TRAIN: ("cityscapes_train",)
  TARGET_DOMAIN:
    TRAIN: ("foggy-cityscapes_train",)
  TRAIN: ("cityscapes_train",)
  TEST: ("foggy-cityscapes_val",)
MODEL:
  META_ARCHITECTURE: "SAPRCNN"
  BACKBONE:
    FREEZE_AT: 1
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  KEYPOINT_ON: False
  MASK_ON: False
  DOMAIN_ADAPTATION_ON: False
  ROI_HEADS:
    NUM_CLASSES: 8
  PROPOSAL_GENERATOR:
    NAME: "SAPRPN"
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
SOLVER:
  IMS_PER_BATCH: 2 # batch size
  STEPS: (80000,)
  BASE_LR: 0.001
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
VIS_PERIOD: 2000
SEED: 11